---
title: "Welcome to the CDU data science team blog"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

We are the data science team within the clinical development unit of [Nottinghamshire Healthcare NHS Trust](https://www.nottinghamshirehealthcare.nhs.uk/):

* [Chris Beeley](https://twitter.com/ChrisBeeley)
* [Zo`r "\u00EB"` Turner](https://lextuga007.github.io/Postcard/)
* [Lori Edwards Suárez](https://twitter.com/Lori_E_S_)

Email the team email at [CDUDataTeam@nottshc.nhs.uk](mailto:cdudatateam@nottshc.nhs.uk)

We believe in open source data science and use R and Python for most of our work. 
We publish as much code and data as we can on our team [GitHub page](https://github.com/CDU-data-science-team). We have a wide range of skills including statistics, machine learning, SQL/ data engineering, Shiny, text mining, and forecasting. We are currently working on nationally funded open source data science projects as well as a range of things within our own Trust, and in the coming weeks and months each team member will present some of this work to you. 

We love to collaborate, to communicate, to meet new people, and to offer (and receive!) advice and support, especially to colleagues in health and social care across the UK (and the world) so please reach out to any of us on Twitter or anywhere else you might come across us or our work.

# Past members of the team

They have moved on to other roles but can still be found here:

* [Andreas Soteriades](https://github.com/andreassot10)
* [Milan Wiedemann](https://github.com/milanwiedemann)
* [Oluwasegun Apejoye](https://www.linkedin.com/in/oluwasegun-michael-apejoye-7b487365/)

# Credit

Pictures are from the British Library flickr collection of [Diagrams, Plots and Charts](https://www.flickr.com/photos/britishlibrary/albums/72157648088610908).