---
title: "Understanding Your Data"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2   
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Background

The CDU Data Science team and Applied Information team initiated a workshop meeting with those interested in "understanding your data" in the first week of March 2021. This was started in response to our need to ensure that the solutions we create are understood by everyone and that we are concentrating on the right problems.

This will be a continuous two-way discussion facilitated by the CDU Data Science Team and will also include analysts from Applied Information and Performance. 

The Understanding Your Data also links into the initiative of Data Clinics where particular specific support has been given to teams with their data. This has been facilitated by our Clinical Analyst.

# Initial request

* Are you interested in understanding your data better?
* Do you have questions about what is going on in your service you feel like you currently can't answer?
* Do you have ideas for ways of presenting and understanding data that you don't have the time to make a reality?
* Would you be interested in looking at data, analyses, and dashboards and feeding back your opinions about them?

Applied Information and the Clinical Development Unit work together to collate, process, and analyse all sorts of datasets for national reporting as well as internal analysis, audit, evaluation, and research. We are trying to make sense of the data in the Trust but we need to hear from people out in services who can tell us what they want and don't want, and can look at analytic products that we make and give us feedback on them.

If you're interested in being a part of the way that the Trust develops its tools for analysing data there are lots of ways you can be involved- coming to a workshop, testing tools in your own time and feeding back your opinions, coming with your own ideas about tools or analyses you would like to see or just commenting on our plans and helping to shape the future of what we produce.

# CDU Data Science Roadmap

The video of the presentation by Chris Beeley is viewable in on the Trust's Microsoft Stream site: https://web.microsoftstream.com/video/41df2da8-eac3-4391-8e0c-a4ef0a853688?list=studio (will require an authorised log in).

https://cdu-data-science-team.github.io/presentations/roadmap/roadmap.html#1

<iframe src="https://cdu-data-science-team.github.io/presentations/roadmap/roadmap.html#1" width="600" height="400" loading="lazy" allowfullscreen></iframe> <script>fitvids('.shareagain', {players: 'iframe'});</script>

# Themes from the events

## Training

Training was something we hadn't considered but came up as a theme. Analysts main software tools are Excel, PowerBI, SQL and R. 

### R

Nottinghamshire Healthcare NHS Foundation Trust allows all staff to access R and R Studio for download through the Software Centre (accessible through the Windows Start button). 

Training is offered through [NHS-R Community](https://nhsrcommunity.com/events/) every month. The course is led by Zoë Turner. Course materials are available [here](https://philosopher-analyst.netlify.app/collection/).

Shiny training is being offered through [NHS-R Community](https://nhsrcommunity.com/events/) and is being designed and led by Chris Beeley. Course materials are available [here](https://github.com/ChrisBeeley/shinyworkshop) and specifically for [beginners](https://github.com/ChrisBeeley/shiny_beginners).

Help for R can be sought from the Slack channel nhsrcommunity.slack.com. Also note that there is a Government Data Science Slack channel govdatascience.slack.com but access to this is restricted to certain email addresses like nhs.net and not individual Trust accounts.

## Mapping

Another general interest that came from the group was mapping data and tools used for this are often QGIS. This is also available through the Software Centre but specific access may be required through IT.

### Public Health Mapping tools

There are a couple of Public Health mapping tools that are available and more information can be found [here](https://cdu-data-science-team.github.io/miscellany/Mapping.html).

## Data clinics

Some individual pieces of work have come out of the Understanding your data meeting and have moved into the data clinic initiative discussed more [here](https://cdu-data-science-team.github.io/team-blog/posts/2021-01-13-data-clinics-in-nottinghamshire-healthcare/)

## Patient Feedback

Nottinghamshire Healthcare NHS Foundation Trust's Patient Feedback (including [Care Opinion](https://www.careopinion.org.uk/services/rha) information) can be found [here](http://suce.co.uk:8080/apps/SUCE/).

# Meeting dates

To try to accommodate as many diaries as possible the day of the meeting will change each month and always be at the same time (1130-1230):

* Tues 2nd March 
* Wed 7th April
* Thurs 6th May
* Fri 4th June


To book on the meeting which will be on MS Teams, please email [Zoë Turner](mailto:zoe.turner2@nottshc.nhs.uk).