---
title: "Secrets in Git"
description: |
  How to ensure that passwords and other secret information isn't shared publicly
author:
  - name: Zoë Turner
    url:
      https://twitter.com/letxuga007: {}
date: 2022-11-09
output:
  distill::distill_article:
    self_contained: false
categories:
  - Open source
  - GitHub
preview: 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

At an NHS-R Community drop in session where we discussed using Git and GitHub one question came up about preventing the version controlling of "secret" information like connection strings to SQL servers. Finding the answer to this had been elusive on the Internet and so this is a blog about how we keep information like this away from GitHub.

# Never ever version control connection code

Many analysts use connections to SQL databases and this is often in R or RMarkdown scripts. We are fortunate enough in the CDU Data Science Team that all our access is through Windows Authentication so we don't have to use any usernames or passwords. If you do, however, need a username and password for any reason then this can be kept in the `.Renviron` file. This is something that the blog about personal access tokens covers, in a section called [The absolutely not recommended method](https://cdu-data-science-team.github.io/team-blog/posts/2021-12-18-personal-access-tokens/#packages-required-1) where details can be placed in the file in the format:

```
GITHUB_PAT=xxxxx
EMAIL=zoe.turner2@nottshc.nhs.uk
```

so that any code that requires the text can be replaced like:

```
conn <- try(pool::dbPool(
    drv = odbc::odbc(),
    driver = driver,
    server = server,
    database = database,
    trusted_connection = TRUE
  ))

```

The `.Renviron` should be outside the project so shouldn't
