---
title: "Understanding Your Data May Meeting"
description: |
  A summary of the discussions at the May Meeting, the frustrations, challenges and considerations of data
author:
  - name: Zoë Turner
    url: https://twitter.com/Letxuga007
date: "2020-05-06"
output:
  distill::distill_article:
    self_contained: false
categories:
  - Understanding Your Data
  - HoNOS
  - Training
  
  
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

It's a great misconception that there are "data people" and there are "non-data people" as **everyone** is a "data person" so long as that data is relevant to them or their work. Whilst you may not necessarily feel you are a "data person", it's often the case that when presented with something that is relevant and incorrect, it's noticed, even if it's not possible to explain why. It's in this context that the success of the Understanding Your Data meetings lies as, whilst people have been coming due to an interest in data, the themed discussions often were similar or very closely related. At the last Understanding Your Data meeting in particular, we discussed some frustrations, challenges and concerns around data in the context of two particular subject areas: HoNOS and incident data. 

## HoNOS (Health of the Nation Outcome Scales)

To explain HoNOS further for context:

[HoNOS (Health of the Nation Outcome Scales)](https://www.rcpsych.ac.uk/events/in-house-training/health-of-nation-outcome-scales)

>The MHCT has been developed in partnership between the Department of Health, the Royal College of Psychiatrists Centre for Advanced Learning and Conferences and the Care Pathways and Packages Project (CPPP) as a means of allocating clients to Care Clusters which in turn supports care planning and enables Mental Health Payment by Results (MH PbR).
>
>HoNOS was published by the Royal College of Psychiatrists (RCPsych) in 1996 and is now the most widely used outcome measure in specialist mental health services in England and overseas. 

is collected throughout many of our mental health services, but we discussed where there will be gaps in this data collection; some services see patients only briefly in the service before being referred onto other services so HoNOS is not collected, also there are differences in how analysts and clinicians use the data as there are rules around Payment By Results (PbR) which mean the data we, analysts, see differs. This is of great importance to the CDU Data Science Team as we are building a package to analyse and visualise the [HoNOS data](https://github.com/CDU-data-science-team/honos) and this domain knowledge helps to inform our understanding and the limitations of any analysis we do.

## Analyst input - using Excel

The other discussions we had, which stemmed from incident data, covered a lot of other general data and analytical points. We started with a discussion on the requirement for analysis and how the particular team requesting needing this used to have a dedicated analyst who brought to the role their domain knowledge as well as analytical expertise. This led to a discussion that covered a bit of what we covered previously in that Excel spreadsheets is a very commonly used tool within the Trust; for many it is often the default tool from teams to senior management. 

Sometimes spreadsheets can just "stop working" as intended and it's these scenarios where the solution of training courses is not really a solution. Courses get people started in using a tool, but to really master any tool, it requires repeated use, and for Excel as well as analysis, this is not the main responsibility for many staff. Knowing who to talk to about problems with spreadsheets or how to analyse things was a common frustration. 

## Training

Nottinghamshire Healthcare NHS Foundation Trust do offer training in Microsoft Office programs and details can be found through the [Intranet pages](https://connect/?page=microsoft-office-365-training). 

For programming in R and R Studio [NHS-R Community](https://nhsrcommunity.com/) do free training for anyone in the public sector on the introduction to R and R Studio. This is run by Zoë Turner in CDU Data Science Team so if a team is in interested in this it a specific course in the Trust can be set up. Course materials are available [here](https://philosopher-analyst.netlify.app/collection/).

## An analytical approach

Some things that were discussed and that will resonate with analysts are that:

* What people ask for in terms of data, may not necessarily be what they want. Often the requests need to be translated or redirected. For example, someone may ask for data by month but because months vary in size it may be better by week. Weeks too need to be determined by what day they start from, is it Monday or is it Sunday? Lori Edwards Suárez from the CDU Data Science Team has written more on [this](https://analystinthewild.wordpress.com/2020/08/09/lost-in-translation/) and has also helped with [Data Clinics](https://cdu-data-science-team.github.io/team-blog/posts/2021-01-13-data-clinics-in-nottinghamshire-healthcare/).
* Data is complex and some colleagues specifically will not analyse anything they have not asked for this reason. These are colleagues who, when they request data, are very detailed and precise in their requests.
* There is a good understanding of how time periods on data extractions can have a significant impact on analysis.
* Gratefulness was expressed for all data that is entered. 
* Dashboards need to include the following information:
  - where the data is from
  - the parameters of the data
  - when was it extracted
  - any caveats to the data, inclusions/exclusions for example
  - timeliness in data, is this data refreshed regularly?
  
* Acknowledgement of how whilst querying why "one number is different to another", it is an unnecessary distraction in meetings where this is not the purpose of the meeting. One solution that works for colleagues is to use a data extract and not refresh this until all queries are resolved. This highlights the need for fixed reports and extracts as dashboards are often refreshed daily and so numbers will change and make it harder to resolve queries.

## Automate

We also discussed how, if you do something twice then it needs automating but this poses problems for those who are not analysts working with data every day as:

* you need to have the tools to automate
* you need to have the skills to automate
* you need to know when automation is possible

## Overall themes

Two other points where we are all data people are that we all:

* Ask ourselves - do I trust this?
* Feel immense frustration when things don't work first time, consistently and in a way that we expect.

Consequently, any organisation needs to consider the following in terms of data use and support for analysis:

* RESOURCE - who is available to do the data cleaning, analysis and understanding. This is often the area of analysts and data scientists but their focus is often directed to specific areas like clinical, HR, or finance. Some data falls outside of these specialisms and accessing support or advice can be difficult.
* METHODOLOGY - all data needs to be provided with caveats, "context", information on the information.
* TRUST - in the data is paramount and this must come from an open and transparent way of working.
* CONTEXT - it must be acknowledged that some people require fixed reports, whilst others want their data straight from a system and so may require dashboards or direct access. The reasons for data requests are based in the context and any analysis must relate to that.

## More information

For more information on the Understanding Your Data initiative please go to the main [page](https://cdu-data-science-team.github.io/team-blog/uyd.html) and feel free to contact members of the CDU Data Science Team by email or through [social media](https://cdu-data-science-team.github.io/team-blog/about.html).



