---
title: "Open source within the NHS - benefits and possible pitfalls"
description: |
  What does open source translate to for the average staff in the NHS? What benefit does this bring to patients? Do patients have reasons to worry more about their privacy?
author:
  - name: Oluwasegun Apejoye
    url: {https://uk.linkedin.com/in/oluwasegun-michael-apejoye}
date: 03-04-2022
output:
  distill::distill_article:
    self_contained: false
categories:
  - Open source    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Introduction  

The health sector is a sensitive sector that needs to prioritize clinical safety and patient data, so embracing open source can really look dreadful and a bad idea. However, the reverse is the case because it's possible to uphold these key issues and still be working in the open. In a simple form, working in the open means making the source codes, that powers our software or application, freely available and downloadable from public platforms such as GitHub. This enables collaboration across the board to maximize benefits for the delivery of health and social care services.  

The term _"open source"_ is no longer a new term, but it's only just starting to gain traction in the NHS. A lot of organizations and tech giants have already started using open source. And, we the [CDU-DS](https://github.com/CDU-data-science-team) (clinical developmental unit – data science) team at NottsHC are at the [forefront of the open-source campaign](https://cdu-data-science-team.github.io/team-blog/posts/2021-02-27-working-in-the-open/) within the NHS. We are dedicated to working in the open and to using open source tools for our analysis, but just like several other teams within the NHS, we're still faced with loads of bottlenecks that are limiting us from harnessing the full potential of open source within our team and trust-wide.

As part of the effort to push for open source, the NSHX has announced that [NHS Open Source Policy will officially become available](open-source-policy/open-source-policy.md at main · nhsx/open-source-policy · GitHub) by this summer. According to the draft document, the policy “aim to provide a single position and source of guidance for anyone developing open software for or with the NHS in England”. The announcement about the policy has been broadly embraced by the NHS-R community (an open community of R users). 

But what does open source translate to for the average staff (with limited technical skills) in the NHS? What benefit does this bring to patients? Do patients have reasons to worry more about their privacy? 

A member of our team already did some justice to this subject matter in her post [working-in-the-open](https://cdu-data-science-team.github.io/team-blog/posts/2021-02-27-working-in-the-open/), where she shared some of her personal experiences and did some justice to the benefit of open source. However, with this post, I hope to share the general benefit and touch on some of the issues about working with open source such as patient privacy etc. 

### Benefits

_Greater collaboration_: open source enables technical (IT experts, Developers, Analyst) and non-technical (clinicians, nurses, GPs) staff to input into projects and collaborate easily. It facilitates easy sharing of software, codes, analytical products etc, and it opens doors for reproducibility. With open source, a small idea can easily become a proof of concept which can grow to become a project that ends up improving care delivery. 

_Cost saving_: using an already published code to serve some aspects of our task will lead to reduced duplication of effort, a reduction in staff time committed to projects and improved staff efficiency, a faster roll-out of cost-saving solutions and it enable teams to pursue the best approaches, not just those available locally.  Also, the awareness of public scrutiny will ensure teams make their projects fit for purpose. In addition, embracing open-source tools means the NHS will benefit from savings from licensing fees as the cost of open-source tools is zero or for instances when the  organisation decide to pay for author's support, costs are cheaper and provides greater commitment/contract flexibility compared to enterprise tools which currently lock-in the organisation to the supplier. 

_Availability of cutting-edge tools_: All open-source projects are available for free and these tools benefit from contributions from a wide variety of users. A good example is the Python and R programming languages, which are widely used tools for a wide range of cool stuff. These two projects have benefited from contributions that now make them a go-to tool for different tasks. 

_Community effort_: The open-source community runs on the philosophy of universally shared knowledge because it benefits from a large and growing network of developers and users that are continually contributing to projects. With an open-source approach to project development, teams from other organizations can take our project, make changes to it and make the changes available to the community (including the original author) to benefit from the additional feature or improvement. This accessibility allows for constant developments and improvements to the software. 

_Safety and Security_: Does open source mean we sacrifice patients' privacy or lose control of projects? No. The organization authoring the project still has the leverage to take on the custodian role on their projects via using the right license agreement and copyrights. Organisations also have the option to explore the various configuration of open-source software they want to use. All these ensure clinical safety is maintained.  

_Additional income stream_: The authoring team of an open source project can offer to provide subscription services, support and maintenance to interested users and therefore generate passive income for their trust. 
 

### What to look out for 

It's a no-brainer that embracing open source will bring several benefits to teams within the healthcare system. However, there are still some pitfalls to look out for. Below are some of the ones I have identified: 

_Possible privacy infringement_: we share code in different formats and some of these can risk exposing sensitive data if not well done. This is usually true when there is no proper training or set of principles to follow before publishing codes. 

_Risk of extra complexity_: with little or no support from the developer of a source code with insufficient documentation (guidance on how to use the code), team risk adding extra complexity to their system with no extra benefit if the component used from that code contains unnecessary functionality. 

_Lack of Warranty_: it is possible to use packages (set of codes) developed by another team in your project. However, there is a risk of the package being abandoned without prior notice by the team and this might introduce some flaws in your application or software. 


To mitigate the above issues, there is a need for robust policies to help analysts, developers and other users follow a consistent approach to open source. And I believe that is where the [NHS Open Source Policy](GitHub - nhsx/open-source-policy: Open Source Policy development for the NHS) proves useful. 

### Conclusion  

Open source has loads of benefits to offer if fully embraced by all teams (both technical and non-technical) within the healthcare system, especially within the NHS where only a fraction of teams currently adopt. Despite these benefits, there is a need for robust open source policies to ensure all teams work in a consistent way that will maximize the benefits for the quality of care delivered to patients, and the efficiency of the health care systems without compromising patient safety and data governance.


If you want to read more about our open source journey, then keep in touch by following us on [Twitter](https://twitter.com/DataScienceNott) and check out our [blog](https://cdu-data-science-team.github.io/team-blog/). 

### Further read 

[NHSX open source policy](open-source-policy/open-source-policy.md at main · nhsx/open-source-policy · GitHub) 

[health care global post](https://healthcareglobal.com/technology-and-ai/nhs-technology-being-open-open-source)

[infocyte blog post](https://www.infocyte.com/blog/2019/06/18/7-risks-posed-by-open-source-software-and-how-to-defend-yourself/) 