on:
  push:
    branches: [main]

name: rebuild_slides

jobs:
  build_slides:
    runs-on: ubuntu-latest
          
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-renv@v1
      
      - name: Install system dependencies
        run: sudo /bin/sh system_requirements.sh

      - name: Cache rendered html files
        uses: actions/cache@v2
        with:
          path: ~/*.html
          key: ${{ runner.os }}-html-1
          
      - name: Build posts
        run: |
          git config --local user.email "CDUDataScience@nottshc.nhs.uk"
          git config --local user.name "CDU Data Science Team"
          make all
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
          single-commit: true